[Graphics]
; Attiva o disattiva le scie gravitazionali (True/False)
trails_enabled = True

; Heatmap di partenza. Valori validi: off, phi_mode, dphi_dt_mode, tidal_mode
starting_heatmap_mode = phi_mode

; Sensibilita visiva della distorsione di Roche e contrasto globale
roche_sensitivity_mag = 0.0
roche_contrast = 15.0

; Offset manuale di sensibilita visiva dell'utente
user_sensitivity_mag = 0.0

; Framerate massimo di rendering
target_fps = 60

[Simulation]
; Raggio iniziale dell'universo simulato (in Unita Astronomiche)
; ATTENZIONE: Questo valore viene usato ESCLUSIVAMENTE per il preset 'Blank' (universo vuoto).
; Per gli altri preset, il raggio viene imposto automaticamente.
simulation_radius_au = 64.0
